import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";
import AuthContextWrapper from "@/components/contexts/AuthContextWrapper";
import AuthLayout from "@/components/shared/AuthLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthContextWrapper>
      <html lang="en" className="dark">
        <body className={cn("min-h-screen", inter.className)}>
          <main className="container mx-auto">
            <Navbar />
            {children}
          </main>
          <Toaster duration={3000} />
        </body>
      </html>
    </AuthContextWrapper>
  );
}
